
from enum import Enum


class NacionalidadeEnum(str, Enum):
    """
    Enum with all nationalities in brasilian portuguese 
    """
    ARGENTINO = "Argentino"
    AFEGÃO = "Afegão"
    ALEMÃ = "Alemã"
    AMERICANO = "Americano"
    ANGOLANO = "Angolano"
    ANTIGUANO = "Antiguano"
    ARGÉLIA = "Argélia"
    ARMENO = "Armeno"
    AUSTRALIANO = "Australiano"
    AUSTRÍAC = "Austríac"
    BAHAMENSE = "Bahamense"
    BANGLADESH = "Bangladesh"
    BECHUANO = "Bechuano"
    BELGA = "Belga"
    BELIZENHO = "Belizenho"
    BOLIVIANO = "Boliviano"
    BRASILEIRO = "Brasileiro"
    CAMARONENSE = "Camaronense"
    CANADENSE = "Canadense"
    CHILENO = "Chileno"
    CHINÊS = "Chinês"
    CINGALÊS = "Cingalês"
    COLOMBIANO = "Colombiano"
    COMORENSE = "Comorense"
    COSTARRIQUENHO = "Costarriquenho"
    CROATA = "Croata"
    CUBANO = "Cubano"
    DINAMARQUÊS = "Dinamarquês"
    DOMINICANA = "Dominicana"
    DOMINICANO = "Dominicano"
    EGÍPCIO = "Egípcio"
    EQUATORIANO = "Equatoriano"
    ESCOCÊS = "Escocês"
    ESLOVACO = "Eslovaco"
    ESLOVENO = "Esloveno"
    ESPANHOL = "Espanhol"
    FILIPINA = "Filipina"
    FRANCÊS = "Francês"
    GALÊS = "Galês"
    GANÉS = "Ganés"
    GRANADINO = "Granadino"
    GREGO = "Grego"
    GUATEMALTECO = "Guatemalteco"
    GUIANENSE = "Guianense"
    GUIANÊS = "Guianês"
    HAITIANO = "Haitiano"
    HOLANDÊS = "Holandês"
    HONDURENHO = "Hondurenho"
    HÚNGARO = "Húngaro"
    IEMENITA = "Iemenita"
    INDIANO = "Indiano"
    INDONÉSIO = "Indonésio"
    INGLÊS = "Inglês"
    IRANIANO = "Iraniano"
    IRAQUIANO = "Iraquiano"
    IRLANDÊS = "Irlandês"
    ISRAELITA = "Israelita"
    ITALIANO = "Italiano"
    JAMAICANO = "Jamaicano"
    JAPONÊS = "Japonês"
    LÍBIO = "Líbio"
    MALAIO = "Malaio"
    MARFINENSE = "Marfinense"
    MARROQUINO = "Marroquino"
    MEXICANO = "Mexicano"
    MOÇAMBICANO = "Moçambicano"
    NAMIBIANA = "Namibiana"
    NEOZELANDÊS = "Neozelandês"
    NEPALÊS = "Nepalês"
    NICARAGUENSE = "Nicaraguense"
    NIGERIANO = "Nigeriano"
    NORTE_COREANO = "Norte-coreano"
    NORUEGO = "Noruego"
    OMANENSE = "Omanense"
    PALESTINO = "Palestino"
    PANAMENHO = "Panamenho"
    PAQUISTANÊS = "Paquistanês"
    PARAGUAIO = "Paraguaio"
    PERUANO = "Peruano"
    POLONÊS = "Polonês"
    PORTORRIQUENHO = "Portorriquenho"
    PORTUGUESA = "Portuguesa"
    QATARENSE = "Qatarense"
    QUENIANO = "Queniano"
    ROMENO = "Romeno"
    RUANDÊS = "Ruandês"
    RUSSO = "Russo"
    SALVADORENHO = "Salvadorenho"
    SANTA_LUCENSE = "Santa-lucense"
    SAUDITA = "Saudita"
    SOMALI = "Somali"
    SUECO = "Sueco"
    SUL_AFRICANO = "Sul-Africano"
    SUL_COREANO = "Sul-coreano"
    SURINAMÊS = "Surinamês"
    SUÍÇO = "Suíço"
    SÃO_CRISTOVENSE = "São-cristovense"
    SÃO_VICENTINO = "São-vicentino"
    SÉRVIO = "Sérvio"
    SÍRIO = "Sírio"
    TAILANDÊS = "Tailandês"
    TIMORENSE = "Timorense"
    TRINDADENSE = "Trindadense"
    TURCO = "Turco"
    UCRANIANO = "Ucraniano"
    UGANDENSE = "Ugandense"
    URUGUAIO = "Uruguaio"
    VENEZUELANO = "Venezuelano"
    VIETNAMITA = "Vietnamita"
    ZIMBABUENSE = "Zimbabuense"
    ZIMBABWEANO = "Zimbabweano"
    BARBADENSE = "barbadense"
    ÁRABE = "Árabe"
    OUTRO = "Outro"

class StatusEnum(str, Enum):
    """
    Enum of Divida states
    """
    FECHADA = "Fechada"
    ANALISE = "Em Análise"
    ABERTA = "Aberta"
    Contestada = "Contestada"
    RENEGOCIADA = "Renegociada"

class EstadoCivil(str, Enum):
    """
    Enum of Divida states
    """
    SOLTEIRO = "Solteiro(a)"
    CASADO = "Casado(a)"
    DIVORCIADO = "Divorciado(a)"
    VIUVO = "Viúvo(a)"
    UNIAO_ESTAVEL = "União Estável"

class TipoUserEnum(str,Enum):
    ADM = "Administrador"
    USER = "Usuario"
    EMPRESA = "Empresa"